// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	vault "github.com/k1nky/gophkeeper/internal/entity/vault"
)

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// GetSecretData mocks base method.
func (m *Mockstorage) GetSecretData(ctx context.Context, id vault.MetaID) (*vault.DataReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretData", ctx, id)
	ret0, _ := ret[0].(*vault.DataReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretData indicates an expected call of GetSecretData.
func (mr *MockstorageMockRecorder) GetSecretData(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretData", reflect.TypeOf((*Mockstorage)(nil).GetSecretData), ctx, id)
}

// GetSecretMeta mocks base method.
func (m *Mockstorage) GetSecretMeta(ctx context.Context, id vault.MetaID) (*vault.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretMeta", ctx, id)
	ret0, _ := ret[0].(*vault.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretMeta indicates an expected call of GetSecretMeta.
func (mr *MockstorageMockRecorder) GetSecretMeta(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretMeta", reflect.TypeOf((*Mockstorage)(nil).GetSecretMeta), ctx, id)
}

// GetSecretMetaByAlias mocks base method.
func (m *Mockstorage) GetSecretMetaByAlias(ctx context.Context, alias string) (*vault.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretMetaByAlias", ctx, alias)
	ret0, _ := ret[0].(*vault.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretMetaByAlias indicates an expected call of GetSecretMetaByAlias.
func (mr *MockstorageMockRecorder) GetSecretMetaByAlias(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretMetaByAlias", reflect.TypeOf((*Mockstorage)(nil).GetSecretMetaByAlias), ctx, alias)
}

// ListSecretsByUser mocks base method.
func (m *Mockstorage) ListSecretsByUser(ctx context.Context) (vault.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecretsByUser", ctx)
	ret0, _ := ret[0].(vault.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecretsByUser indicates an expected call of ListSecretsByUser.
func (mr *MockstorageMockRecorder) ListSecretsByUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecretsByUser", reflect.TypeOf((*Mockstorage)(nil).ListSecretsByUser), ctx)
}

// PutSecret mocks base method.
func (m *Mockstorage) PutSecret(ctx context.Context, meta vault.Meta, data *vault.DataReader) (*vault.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSecret", ctx, meta, data)
	ret0, _ := ret[0].(*vault.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutSecret indicates an expected call of PutSecret.
func (mr *MockstorageMockRecorder) PutSecret(ctx, meta, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSecret", reflect.TypeOf((*Mockstorage)(nil).PutSecret), ctx, meta, data)
}

// Mockclient is a mock of client interface.
type Mockclient struct {
	ctrl     *gomock.Controller
	recorder *MockclientMockRecorder
}

// MockclientMockRecorder is the mock recorder for Mockclient.
type MockclientMockRecorder struct {
	mock *Mockclient
}

// NewMockclient creates a new mock instance.
func NewMockclient(ctrl *gomock.Controller) *Mockclient {
	mock := &Mockclient{ctrl: ctrl}
	mock.recorder = &MockclientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclient) EXPECT() *MockclientMockRecorder {
	return m.recorder
}

// GetSecretData mocks base method.
func (m *Mockclient) GetSecretData(ctx context.Context, id vault.MetaID, w io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretData", ctx, id, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetSecretData indicates an expected call of GetSecretData.
func (mr *MockclientMockRecorder) GetSecretData(ctx, id, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretData", reflect.TypeOf((*Mockclient)(nil).GetSecretData), ctx, id, w)
}

// GetSecretMeta mocks base method.
func (m *Mockclient) GetSecretMeta(ctx context.Context, id vault.MetaID) (*vault.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretMeta", ctx, id)
	ret0, _ := ret[0].(*vault.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretMeta indicates an expected call of GetSecretMeta.
func (mr *MockclientMockRecorder) GetSecretMeta(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretMeta", reflect.TypeOf((*Mockclient)(nil).GetSecretMeta), ctx, id)
}

// ListSecrets mocks base method.
func (m *Mockclient) ListSecrets(ctx context.Context) (vault.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", ctx)
	ret0, _ := ret[0].(vault.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockclientMockRecorder) ListSecrets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*Mockclient)(nil).ListSecrets), ctx)
}

// PutSecret mocks base method.
func (m *Mockclient) PutSecret(ctx context.Context, meta vault.Meta, r io.Reader) (*vault.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSecret", ctx, meta, r)
	ret0, _ := ret[0].(*vault.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutSecret indicates an expected call of PutSecret.
func (mr *MockclientMockRecorder) PutSecret(ctx, meta, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSecret", reflect.TypeOf((*Mockclient)(nil).PutSecret), ctx, meta, r)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Debugf mocks base method.
func (m *Mocklogger) Debugf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockloggerMockRecorder) Debugf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*Mocklogger)(nil).Debugf), varargs...)
}

// Errorf mocks base method.
func (m *Mocklogger) Errorf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockloggerMockRecorder) Errorf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*Mocklogger)(nil).Errorf), varargs...)
}
