// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	user "github.com/k1nky/gophkeeper/internal/entity/user"
	vault "github.com/k1nky/gophkeeper/internal/entity/vault"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockauthService) Authorize(token string) (user.PrivateClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", token)
	ret0, _ := ret[0].(user.PrivateClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockauthServiceMockRecorder) Authorize(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockauthService)(nil).Authorize), token)
}

// Login mocks base method.
func (m *MockauthService) Login(ctx context.Context, u user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, u)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthServiceMockRecorder) Login(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthService)(nil).Login), ctx, u)
}

// Register mocks base method.
func (m *MockauthService) Register(ctx context.Context, u user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, u)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockauthServiceMockRecorder) Register(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockauthService)(nil).Register), ctx, u)
}

// MockkeeperService is a mock of keeperService interface.
type MockkeeperService struct {
	ctrl     *gomock.Controller
	recorder *MockkeeperServiceMockRecorder
}

// MockkeeperServiceMockRecorder is the mock recorder for MockkeeperService.
type MockkeeperServiceMockRecorder struct {
	mock *MockkeeperService
}

// NewMockkeeperService creates a new mock instance.
func NewMockkeeperService(ctrl *gomock.Controller) *MockkeeperService {
	mock := &MockkeeperService{ctrl: ctrl}
	mock.recorder = &MockkeeperServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkeeperService) EXPECT() *MockkeeperServiceMockRecorder {
	return m.recorder
}

// GetSecretData mocks base method.
func (m *MockkeeperService) GetSecretData(ctx context.Context, uk vault.UniqueKey) (*vault.DataReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretData", ctx, uk)
	ret0, _ := ret[0].(*vault.DataReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretData indicates an expected call of GetSecretData.
func (mr *MockkeeperServiceMockRecorder) GetSecretData(ctx, uk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretData", reflect.TypeOf((*MockkeeperService)(nil).GetSecretData), ctx, uk)
}

// GetSecretMeta mocks base method.
func (m *MockkeeperService) GetSecretMeta(ctx context.Context, uk vault.UniqueKey) (*vault.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretMeta", ctx, uk)
	ret0, _ := ret[0].(*vault.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretMeta indicates an expected call of GetSecretMeta.
func (mr *MockkeeperServiceMockRecorder) GetSecretMeta(ctx, uk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretMeta", reflect.TypeOf((*MockkeeperService)(nil).GetSecretMeta), ctx, uk)
}

// ListSecretsByUser mocks base method.
func (m *MockkeeperService) ListSecretsByUser(ctx context.Context, userID user.ID) (vault.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecretsByUser", ctx, userID)
	ret0, _ := ret[0].(vault.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecretsByUser indicates an expected call of ListSecretsByUser.
func (mr *MockkeeperServiceMockRecorder) ListSecretsByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecretsByUser", reflect.TypeOf((*MockkeeperService)(nil).ListSecretsByUser), ctx, userID)
}

// PutSecret mocks base method.
func (m *MockkeeperService) PutSecret(ctx context.Context, meta vault.Meta, data *vault.DataReader) (*vault.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSecret", ctx, meta, data)
	ret0, _ := ret[0].(*vault.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutSecret indicates an expected call of PutSecret.
func (mr *MockkeeperServiceMockRecorder) PutSecret(ctx, meta, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSecret", reflect.TypeOf((*MockkeeperService)(nil).PutSecret), ctx, meta, data)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Debugf mocks base method.
func (m *Mocklogger) Debugf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockloggerMockRecorder) Debugf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*Mocklogger)(nil).Debugf), varargs...)
}

// Errorf mocks base method.
func (m *Mocklogger) Errorf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockloggerMockRecorder) Errorf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*Mocklogger)(nil).Errorf), varargs...)
}

// Infof mocks base method.
func (m *Mocklogger) Infof(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockloggerMockRecorder) Infof(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*Mocklogger)(nil).Infof), varargs...)
}
